name: Test Data Pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Python 3.12.0
      - name: Set up Python version 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      # Setup kaggle by creating kaggle.json at project/.config
      - name: Set up kaggle
        run: |
          cd ./project/.config
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > kaggle.json
          chmod 600 kaggle.json
          cd ../../
      
      # Execute test pipeline
      - name: CI of test data pipeline
        run: |
          cd ./project
          chmod +x tests.sh
          echo "CI test data pipeline - START"
          bash tests.sh
          exit 0
        continue-on-error: true

      # Store exit code
      - name: Store exit code
        id: store_exit_code
        run: echo "EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Print custom success message
        if: ${{ env.EXIT_CODE == 0 }}
        run: |
          echo "Success: CI test data pipeline."

      - name: Print custom failure message
        if: ${{ env.EXIT_CODE != 0 }}
        run: |
          echo "Failure: CI test data pipeline."
